# Generated by Django 6.0.3 on 2026-05-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='confirmacion_automatica',
            field=models.BooleanField(default=True, help_text='Si está activo, las reservas de este espacio se aprueban automáticamente. Desactívalo si requieren aprobación manual del administrador.', verbose_name='Confirmación automática de reservas'),
        ),
    ]
