# Generated by Django 6.0.3 on 2026-05-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de reserva')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, help_text='Describe brevemente el propósito de la reserva.', null=True, verbose_name='Motivo / Descripción')),
                ('observaciones_admin', models.TextField(blank=True, help_text='Notas internas del administrador al aprobar o cancelar.', null=True, verbose_name='Observaciones del administrador')),
                ('confirmacion_automatica', models.BooleanField(default=False, help_text='Si está activo, la reserva se aprueba automáticamente al crearse.', verbose_name='Confirmación automática')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espacios.espacio', verbose_name='Espacio')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espacios.horario', verbose_name='Horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-fecha_creacion'],
                'unique_together': {('espacio', 'horario', 'fecha')},
            },
        ),
    ]
